### ISSUE TITLE
Bash cfv tool

### ISSUE THREAD

**Issue by jarppiko** [cfv-project/cfv#34]
Hello, 

I haven't been able to run the Python 2.7 based cfv for years on a stock Ubuntu due to some dependencies.  As a long-time user of (Python-based) `cfv`, I decided to write a Bash script to do roughly the same thing and with less dependencies to "often" (once a decade) changing libs, modules. Just in case someone is interested. 

Bash [bcfv](https://github.com/jarppiko/bcfv)

"Tested and works on Linux"

**Comment by lxp** [comment]
Hi @jarppiko,

We have a working Python 3 variant of `cfv` since a few months (see https://github.com/cfv-project/cfv/issues/8#issuecomment-1108436629).
Since there are no known issues with it, I will release 3.0.0 soon, but you can already install it right now via pip.
I will compile an alternative tool list from the comments already discussed by other people and also add your tool to this list.

**Comment by lxp** [comment]
Just one other thing, but please do not understand it the wrong way:
I think it is a good thing to have multiple tools around and thanks for developing it.
However, the name of your tool might be a bit misleading for long-term users of the good old `cfv`.
Did you think about giving your tool a slightly different name than the original `cfv`, for example `bcfv` or something like that?

**Comment by jarppiko** [comment]
Hello @lxp, 

First, my sincerest apologies. It did not occur to me that using the same program name could be felt bit offending. I will fix this right away. I am so sorry about this. And thank you for saving me time and comping up with a good name - `bcsv`, it will be. 

[bcfv](https://github.com/jarppiko/bcfv) - A Bash frontend to checksum programs (SHA, Blake3, MD5)

- [x] Rename repo to [bcfv](https://github.com/jarppiko/bcfv)
- [x] Rename script to `bcfv`

**Comment by lxp** [comment]
Thank you! I have included your tool in the alternative tools list in the README.md.
